<?php
include("./header.php");

?>

  <!--================Home Banner Area =================-->
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Privacy & Policy</h2>
                            <p>Home <span>-</span> Privacy & Policy</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--================Blog Area =================-->
    <section class="blog_area padding_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mb-12 mb-lg-12">
                    <div class="blog_left_sidebar">
<h3> Terms & Conditions </h3>
<br><br>
      <h4>General Terms </h4> <p>
By Accessing and Placing an Order with Varni String & Art, You Confirm That You Are in Agreement with and Bound by The Terms of Service Contained in The Terms & Conditions Outlined Below. These Terms Apply To The Entire Website And Any Email Or Other Type Of Communication Between You And Varni String & Art Under No Circumstances Shall Varni String & Art Team Be Liable For Any Direct, Indirect, Special, Incidental, Or Consequential Damages, Including, But Not Limited To, Loss Of Data Or Profit, Arising Out Of The Use, Or The Inability To Use, The Materials On This Site, Even If Varni String & Art The Team Or An Authorized Representative Has Been Advised Of The Possibility Of Such Damages. If Your Use of Materials from This, Site Results in The Need for Servicing, Repair, Or Correction of Equipment or Data, You Assume Any Costs Thereof. Varni String & Art Will Not Be Responsible for Any Outcome That May Occur During the Usage of Our Resources. We have the right to Change Prices and Revise the Resources Usage Policy at Any Moment.
</p> <br><br>

<h4>License </h4>
<p>
Varni String & Art Grants You a Revocable, Non-Exclusive, Non-Transferable, Limited License to Download, Install and Use the Website Strictly Following the Terms of This Agreement. These Terms & Conditions Are a Contract Between You and Varni String & Art ("We," “Our,” Or "The Us") Grants You a Revocable, Non-Exclusive, 
Non-Transferable, Limited License to Download,
 Install and Use the Website Strictly following The Terms of This Agreement.</p>
 <br><br>

<h4>Definitions and Key Terms (For This Terms & Conditions): </h4>
<p>

* Cookie: A Small Amount of Data Is Generated by A Website and Saved by Your Web Browser. It Is Used to Identify Your Browser, Provide Analytics, And Remember Information About You Such as Your Language Preference or Login Information.<br>
* Company: When This Policy Mentions “Company”, “We”, “Us” Or “Our” It Refers to Varni String & Art That Is Responsible for Your Information Under This Privacy Policy.<br>
* Country: Where Varni String & Art or The Owners/Founders of Varni String & Art Are Based, In This Case, Is India.<br>
* Customer: Refers to The Company, Organization, Or Person That Signs Up to Use the Varni String & Art Service to Manage the Relationships with Your Consumers or Service Users.<br>
* Device: Any Internet-Connected Device Such as A Phone, Tablet, Computer, Or Any Other Device That Can Be Used to Visit Varni String & Art and Use the Services.<br>
* IP Address: Every Device Connected to The Internet Is Assigned a Number Known as an Internet Protocol (IP) Address. These Numbers Are Usually Assigned in Geographic Blocks. An IP Address Can Often Be Used to Identify the Location from Which a Device Is Connecting to The Internet.<br>
* Personnel: Refers to Those Individuals Who Are Employed by Varni String & Art or Are under Contract to Perform a Service on Behalf of One of the Parties.<br>
* Personal Data: Any Information That Directly, Indirectly, or in Connection with Other information — Including A Personal Identification Number — Allows for The Identification of a Natural Person.<br>
* Service: Refers to The Service Provided by Varni String & Art as Described in The Relative Terms (If Available) And on This Platform.<br>
* Third-Party Service: Refers to Advertisers, Contest Sponsors, Promotional and Marketing Partners, And Others Who Provide Us Content or Whose Products or Services We Think May Interest You.<br>
* Website: Varni String & Art Site, Which Can Be Accessed Via This Url: Http://Varni String<br>
* You: A Person or Entity That Is Registered with Varni String & Art to Use the Services.<br>
</p>
 <br><br>

<h4>Restrictions (You Agree Not to, And You Will Not Permit Others Too): </h4>
<p>
    * License, Sell, Rent, Lease, Assign, Distribute, Transmit, Host, Outsource, Disclose or Otherwise Commercially
Exploit the Service or Make the Platform Available to Any Third Party.<br>
* Modify, Make Derivative Works of, Disassemble, Decrypt, Reverse Compile, or Reverse Engineer Any Part of the Service.<br>
* Remove, Alter or Obscure Any Proprietary Notice (Including Any Notice of Copyright or Trademark) Of or Its Affiliates, Partners, Suppliers, or The Licensors of the Service.</p>

                      
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->

<?php
include("./footer.php");

?>